#!/usr/bin/env python3
import pandas as pd
import hashlib
import sys

def compute_file_hash(file_path):
    """Compute MD5 hash of a file"""
    hash_md5 = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

def compare_csv_content(file1, file2):
    """Compare two CSV files by reading them into pandas and checking equality"""
    try:
        df1 = pd.read_csv(file1)
        df2 = pd.read_csv(file2)
        
        # Check if the DataFrames have the same shape
        if df1.shape != df2.shape:
            print(f"Files have different shapes: {df1.shape} vs {df2.shape}")
            return False
            
        # Check if the DataFrames have the same column names
        if not all(df1.columns == df2.columns):
            print("Files have different column names")
            return False
            
        # Check if all data is identical
        if not df1.equals(df2):
            # Find differences
            differences = 0
            for col in df1.columns:
                if not df1[col].equals(df2[col]):
                    different_rows = (df1[col] != df2[col]).sum()
                    print(f"Column '{col}' has {different_rows} different values")
                    
                    # Show a sample of differences for debugging
                    if different_rows > 0:
                        diff_indices = (df1[col] != df2[col])
                        sample_idx = diff_indices[diff_indices].index[0]
                        print(f"Example difference at row {sample_idx}:")
                        print(f"  File 1: '{df1.loc[sample_idx, col]}'")
                        print(f"  File 2: '{df2.loc[sample_idx, col]}'")
                    
                    differences += different_rows
            print(f"Total differences: {differences}")
            return False
            
        return True
    except Exception as e:
        print(f"Error comparing files: {e}")
        return False

def main():
    file1 = "data/vss_data.csv"  # Generated by make_vss_csv.py
    file2 = "data/vss_data_unified.csv"  # Generated by unify_institutions.py
    
    print(f"Comparing: {file1} and {file2}")
    
    # First check: file hashes
    hash1 = compute_file_hash(file1)
    hash2 = compute_file_hash(file2)
    
    print(f"\nFile 1 MD5: {hash1}")
    print(f"File 2 MD5: {hash2}")
    
    if hash1 == hash2:
        print("\n✅ Files are identical (same MD5 hash)")
        return 0
    else:
        print("\n⚠️ Files have different hashes, performing detailed comparison...")
        
        # Detailed comparison
        if compare_csv_content(file1, file2):
            print("\n✅ Files have identical content (same data values)")
            return 0
        else:
            print("\n❌ Files have different content")
            return 1

if __name__ == "__main__":
    sys.exit(main()) 